// Colors matching ElasticLend frontend
export const COLORS = {
  bg: '#0A0A0A',
  surface: '#141414',
  elevated: '#1E1E1E',
  accent: '#C8553D',
  accentDim: '#A8432F',
  text: '#E8E4DC',
  textSecondary: '#9B9689',
  textMuted: '#6B6560',
  success: '#2ECC71',
  danger: '#E74C3C',
  warning: '#E67E22',
  paper: '#F5F0E8',
};

export const FPS = 30;
export const WIDTH = 1920;
export const HEIGHT = 1080;

// Subtitle data with corrected timestamps (in seconds)
export const CAPTIONS: { start: number; end: number; text: string }[] = [
  { start: 2, end: 8, text: 'ElasticLend: Elastic Restaking Networks Applied to Lending' },
  { start: 8, end: 18, text: 'A cross-chain lending protocol with portfolio-aware collateral management' },
  { start: 20, end: 30, text: 'The elastic restaking paper (Bar-Zur & Eyal, ACM CCS 2025) proves elastic allocation is strictly more robust than rigid' },
  { start: 32, end: 42, text: 'Lending portfolios are structurally identical to restaking networks. The paper\'s theorems apply directly.' },
  { start: 42, end: 52, text: 'Rigid: BP = Collateral - sum(expected losses). Treats all risk as perfectly correlated.' },
  { start: 52, end: 62, text: 'Elastic: BP = Collateral - sqrt(sum(losses squared)). Uncorrelated risks partially cancel out.' },
  { start: 62, end: 68, text: '"Diversified collateral is strictly safer. Rigid models punish both equally."' },
  { start: 70, end: 80, text: 'Figure 1: Portfolio Simulator. Building a collateral portfolio to compare elastic vs rigid.' },
  { start: 82, end: 90, text: 'No tokens selected yet. Rigid and Elastic borrowing power both at $0.' },
  { start: 90, end: 100, text: 'Adding 5 ETH ($10,575) on Ethereum. Single asset: Rigid = Elastic = $5,288. No diversification.' },
  { start: 100, end: 108, text: 'With one risk group, elastic offers no advantage. The sqrt of one squared number equals itself.' },
  { start: 108, end: 120, text: 'Adding 5,000 USDC on Arbitrum. Second risk group (STABLE). Elastic advantage appears.' },
  { start: 120, end: 134, text: 'ETH + USDC: Rigid $10,038 vs Elastic $10,282. Cross-chain diversification starts to show.' },
  { start: 136, end: 148, text: 'Adding 0.2 wBTC ($13,859) on Base. Third risk group (BTC). Elastic advantage: +20.4%' },
  { start: 148, end: 156, text: 'Rigid $17,660 vs Elastic $21,254. Three uncorrelated risk groups compress the expected loss.' },
  { start: 158, end: 168, text: 'Adding 300 LINK ($2,679). Fourth risk group (OTHER). All four groups now active.' },
  { start: 170, end: 180, text: 'Setting LINK to 300 tokens. Final portfolio across 4 risk groups on multiple chains.' },
  { start: 180, end: 192, text: 'Final: Rigid BP $18,732 vs Elastic BP $23,777. Elastic advantage: +26.9%' },
  { start: 192, end: 202, text: 'Same $32,113 in collateral. Elastic gives 27% more borrowing power. HHI: 3,259.' },
  { start: 202, end: 214, text: 'HHI measures portfolio concentration. 10,000 = single group. 2,500 = perfectly diversified across 4 groups.' },
  { start: 216, end: 226, text: 'The elastic model computes loss per risk group, then takes the L2 norm. BP = Total - sqrt(sum EL_g squared).' },
  { start: 228, end: 236, text: 'Scrolling to Figure 2: Crash Simulator. What happens when the market crashes?' },
  { start: 236, end: 246, text: 'Health Factor = Borrowing Power / Debt. Position is liquidated when HF drops below 1.0.' },
  { start: 248, end: 258, text: 'Four crash sliders, one per risk group. All at 0%. Debt set to $18,000.' },
  { start: 258, end: 270, text: 'No crash yet. Rigid HF: 1.04 (barely safe). Elastic HF: 1.32 (comfortable). Both SURVIVE.' },
  { start: 270, end: 284, text: 'Same debt, same collateral, no crash. But elastic sees 28% more safety margin from diversification.' },
  { start: 284, end: 298, text: 'The safety margins are very different. Rigid barely clears 1.0. Elastic has room to absorb a crash.' },
  { start: 300, end: 310, text: 'Now dragging ETH crash slider to 40%. Watch the gauges diverge.' },
  { start: 312, end: 322, text: 'ETH crashes 40%. Rigid HF: 0.92 LIQUIDATED. Elastic HF: 1.15 SURVIVES.' },
  { start: 322, end: 334, text: 'Same portfolio. Same crash. Same debt. Rigid is liquidated. Elastic survives.' },
  { start: 334, end: 346, text: 'The diversification across BTC, USDC, and LINK absorbs the ETH shock in the elastic model.' },
  { start: 346, end: 356, text: 'Rigid treats every asset independently and panics. Elastic measures risk as a portfolio.' },
  { start: 358, end: 370, text: 'The chart shows elastic BP (orange) staying above the $18,000 debt line. Rigid (gray) crosses below.' },
  { start: 370, end: 382, text: 'Pre-crash: $32,113. Post-crash: $27,883. Capital saved by elastic model: $4,083.' },
  { start: 384, end: 396, text: 'Scrolling to Figure 3: The Stretch Effect. What happens after partial liquidation?' },
  { start: 396, end: 408, text: 'Portfolio bars show each risk group. BTC is the most concentrated at 43.2%.' },
  { start: 408, end: 420, text: 'The stretch effect: when the most impaired collateral is seized, remaining collateral stretches.' },
  { start: 420, end: 434, text: 'This is Section 3.4 of the paper: elastic slashing. Remaining allocations expand after a service fails.' },
  { start: 436, end: 446, text: 'About to click "LIQUIDATE MOST IMPAIRED" to seize 50% of BTC.' },
  { start: 448, end: 458, text: 'Clicked. BTC reduced from $13,859 to $6,930. Portfolio rebalances toward safer assets.' },
  { start: 458, end: 468, text: 'After liquidation: HHI drops from 3,259 to 3,028 (more diversified).' },
  { start: 468, end: 478, text: 'BP per dollar: BEFORE 74.0%, AFTER 74.8%. The collateral stretched. +0.7 percentage points.' },
  { start: 478, end: 490, text: 'BP per dollar INCREASED after liquidation. The remaining portfolio is safer per dollar of collateral.' },
  { start: 490, end: 502, text: 'No other lending protocol does this. Rigid models keep the same fixed factors after liquidation.' },
  { start: 502, end: 514, text: 'Table 1: The Isomorphism. Validators = Borrowers. Services = Risk Factors. The mapping is exact.' },
  { start: 514, end: 526, text: 'Every theorem about restaking security translates directly to elastic borrowing power.' },
  { start: 526, end: 535, text: 'Based on IC3 research: Elastic Restaking Networks (Bar-Zur & Eyal, ACM CCS 2025)' },
];
